# Generated by Django 4.2.30 on 2026-09-15 08:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_field", "0001_inherit_from_custom_base_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="customvalue",
            name="external_label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Externe Bezeichnung",
            ),
        ),
        migrations.AddConstraint(
            model_name="customvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_label", ""), _negated=True),
                fields=("field", "external_label"),
                name="custom_value_field_external_label_unique",
            ),
        ),
    ]
