# Generated by Django 4.2.23 on 2025-11-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_fields", "0006_add_filterable_to_customfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
