# Generated by Django 4.2.23 on 2025-10-09 05:44

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("custom_fields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("firstname", models.CharField(verbose_name="firstname")),
                (
                    "lastname",
                    models.CharField(blank=True, null=True, verbose_name="lastname"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                (
                    "custom_values",
                    models.ManyToManyField(
                        blank=True,
                        to="custom_fields.customvalue",
                        verbose_name="Benutzerdefinierte Werte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("city", models.CharField(blank=True, verbose_name="city")),
                ("country", models.CharField(blank=True, verbose_name="country")),
                ("street", models.CharField(blank=True, verbose_name="street")),
                ("zip_code", models.CharField(blank=True, verbose_name="postal code")),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "custom_values",
                    models.ManyToManyField(
                        blank=True,
                        to="custom_fields.customvalue",
                        verbose_name="Benutzerdefinierte Werte",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
