# Generated by Django 4.2.23 on 2025-10-09 08:55

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_add_person_type_and_relation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(unique=True, verbose_name="title")),
            ],
            options={
                "verbose_name": "Municipality",
                "verbose_name_plural": "Municipalities",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="place_of_residence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="persons",
                to="app.municipality",
                verbose_name="Place of residence",
            ),
        ),
    ]
