# Generated by Django 4.2.23 on 2025-10-09 10:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_add_model_municipality"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="external_uid",
            field=models.UUIDField(null=True, verbose_name="external uid"),
        ),
    ]
