# Generated by Django 4.2.23 on 2025-10-23 05:26

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_add_external_uid_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("uid", models.UUIDField(unique=True, verbose_name="UUID")),
                ("title", models.CharField(unique=True, verbose_name="Title")),
                ("number", models.CharField(verbose_name="Number")),
            ],
            options={
                "verbose_name": "Election district",
                "verbose_name_plural": "Election districts",
                "ordering": ("title",),
            },
        ),
        migrations.AddField(
            model_name="person",
            name="election_district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="persons",
                to="app.electiondistrict",
                verbose_name="Election district",
            ),
        ),
    ]
