# Generated by Django 4.2.23 on 2026-02-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_electiondistrict_person_election_district"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="custom_values",
        ),
        migrations.RemoveField(
            model_name="person",
            name="custom_values",
        ),
    ]
