# Generated by Django 4.2.23 on 2026-02-24 14:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_field", "0001_inherit_from_custom_base_model"),
        ("app", "0006_remove_custom_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="custom_values",
            field=models.ManyToManyField(
                blank=True,
                to="custom_field.customvalue",
                verbose_name="Benutzerdefinierte Werte",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="custom_values",
            field=models.ManyToManyField(
                blank=True,
                to="custom_field.customvalue",
                verbose_name="Benutzerdefinierte Werte",
            ),
        ),
    ]
