name: Tests

on:
  - push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        django:
          - "~=4.2.0"
          - "~=5.2.0"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django_features_testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 2.1
      - name: Install dependencies
        run: |
          poetry install
          poetry run pip install "Django${{ matrix.django }}"
      - name: isort
        run: poetry run isort --check-only --quiet --settings pyproject.toml .
      - name: flake8
        run: poetry run flake8
      - name: black
        run: poetry run black --check --config pyproject.toml .
      - name: mypy
        run: poetry run mypy django_features app
      - name: test
        run: DJANGO_CONFIGURATION=Testing poetry run pytest
